name: pygeoapi
channels:
  - defaults
  - conda-forge
dependencies:
  - conda-forge::python==3.11.7
  - conda-forge::pip==24.3.1
  - conda-forge::gdal==3.9.3
  - conda-forge::libgdal-arrow-parquet==3.9.3
  - conda-forge::pyinstaller==6.11.1
  - conda-forge::Pillow==11.0.0
  - pip:
      - -e ./
      - pygeofilter==0.2.4
      - -r requirements-admin.txt
      - flask-cors==5.0.0
