name: Build Binary

on:
  push:
    branches: [feat-os-build]
  pull_request:
    branches: [main]

env:
  MICROMAMBA_ENV_NAME: pygeoapi
  GDAL_VERSION: 3.10.0

jobs:
  build:
    timeout-minutes: 30
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Micromamba
        uses: mamba-org/setup-micromamba@v1.11.0
        with:
          micromamba-version: "1.5.10-0"
          environment-file: environment.yaml
          environment-name: ${{ env.MICROMAMBA_ENV_NAME }}
          init-shell: bash
          cache-environment: false
          post-cleanup: all
          log-level: info
        env:
          ACTIONS_STEP_DEBUG: true

      - name: Setup GDAL and Environment Variables (Windows only)
        if: matrix.os == 'windows-latest'
        shell: cmd
        run: |
          setx GDAL_DATA "%CONDA_PREFIX%\Library\share\gdal"
          setx PROJ_LIB "%CONDA_PREFIX%\Library\share\proj"
          setx GDAL_CONFIG "%CONDA_PREFIX%\Library\bin\gdal-config"
          setx PATH "%CONDA_PREFIX%\Library\bin;%PATH%"

      - name: Build Rasterio (Windows)
        if: matrix.os == 'windows-latest'
        shell: cmd
        run: |
          echo [build_ext] > setup.cfg
          echo include_dirs=%CONDA_PREFIX%\Library\include >> setup.cfg
          echo libraries=gdal >> setup.cfg
          echo library_dirs=%CONDA_PREFIX%\Library\lib >> setup.cfg
          micromamba run -n %MICROMAMBA_ENV_NAME% python -m pip install --no-binary rasterio rasterio

      - name: Build Rasterio (macOS and Ubuntu)
        if: matrix.os != 'windows-latest'
        shell: bash
        run: |
          micromamba run -n ${{ env.MICROMAMBA_ENV_NAME }} pip install --no-binary rasterio --no-deps --force-reinstall rasterio

      - name: Build the Package
        shell: bash
        run: |
          micromamba run -n ${{ env.MICROMAMBA_ENV_NAME }} pyinstaller pygeoapi.spec --clean

      - name: Upload Artifact
        uses: actions/upload-artifact@v4.4.0
        with:
          name: binary-${{ matrix.os }}
          path: dist/ # Adjust this path if necessary
