name: Build Binary

on:
  push:
    branches: [feat-os-build]
  pull_request:
    branches: [main]

env:
  MICROMAMBA_ENV_NAME: pygeoapi
  GDAL_VERSION: 3.9.3
  RASTERIO_VERSION: 1.3.11

jobs:
  build:
    timeout-minutes: 30
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Micromamba
        uses: mamba-org/setup-micromamba@v1.11.0
        with:
          micromamba-version: "1.5.10-0"
          # micromamba-binary-path: ${{ runner.temp }}/bin/micromamba
          environment-file: environment.yaml
          environment-name: ${{ env.MICROMAMBA_ENV_NAME }}
          init-shell: bash
          cache-environment: false
          post-cleanup: all
          log-level: info
        env:
          ACTIONS_STEP_DEBUG: true

      - name: Upgrade Dependencies
        shell: bash
        run: |
          micromamba run -n ${{ env.MICROMAMBA_ENV_NAME }} pip install --upgrade --no-deps --force-reinstall numpy pyinstaller

      - name: Downgrade rasterio version
        shell: bash
        run: |
          micromamba run -n ${{ env.MICROMAMBA_ENV_NAME }} pip install rasterio==${{ env.RASTERIO_VERSION }} --force-reinstall

      - name: Build the Package
        shell: bash
        run: |
          micromamba run -n ${{ env.MICROMAMBA_ENV_NAME }} pyinstaller pygeoapi.spec --clean

      - name: Upload Artifact
        uses: actions/upload-artifact@v4.4.0
        with:
          name: binary-${{ matrix.os }}
          path: dist/ # Adjust this path if necessary
