name: Check Vulnerabilities TEST-ONLY-TO-BE-DELETED

on:
  push:
    paths-ignore:
      - "**.md"
  pull_request:
    branches:
      - master
    paths-ignore:
      - "**.md"
  release:
    types:
      - released

jobs:
  vulnerabilities:
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: .
    steps:
      - name: Checkout pygeoapi
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Scan vulnerabilities with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: fs
          exit-code: 1
          ignore-unfixed: true
          severity: CRITICAL,HIGH
          scanners: vuln,misconfig,secret
          scan-ref: .
          skip-dirs: .cache

      - name: Build and Push Docker Image
        run: |
          IMAGE_NAME="${{ secrets.DOCKERHUB_USERNAME }}/pygeoapi"
          IMAGE_TAG="${{ github.sha }}"
          docker buildx build --push -t ${IMAGE_NAME}:${IMAGE_TAG} --platform linux/amd64 --no-cache -f Dockerfile .
          echo "IMAGE_NAME=${IMAGE_NAME}" >> $GITHUB_ENV
          echo "IMAGE_TAG=${IMAGE_TAG}" >> $GITHUB_ENV

      - name: Scan Docker Image for Vulnerabilities with Trivy
        uses: aquasecurity/trivy-action@master
        env:
          TRIVY_DB_REPOSITORY: public.ecr.aws/aquasecurity/trivy-db:2
          TRIVY_JAVA_DB_REPOSITORY: public.ecr.aws/aquasecurity/trivy-java-db:1
        with:
          scan-type: image
          exit-code: 1
          ignore-unfixed: true
          severity: CRITICAL,HIGH
          vuln-type: os,library
          image-ref: "${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}"
